# 김용재 전처리

In [2]:
import pandas as pd

In [3]:
main_df = pd.read_csv('노가다전_단속장소.csv',encoding='cp949')

In [4]:
sub_df = pd.read_csv('노가다_종합.csv',encoding='cp949')

In [5]:
main_df.drop(['Unnamed: 0'],axis=1, inplace=True)

In [6]:
main_df

                   단속일시                        단속장소           X           Y
0        2020.1.1 11:14          서울특별시 양천구 목동 901-3  126.872374  37.5374572
1        2020.1.1 13:15         서울특별시 양천구 신월동 88-31  126.835014  37.5371132
2        2020.1.1 15:07         서울특별시 양천구 신정동 212-1  126.866868  37.5098806
3        2020.1.1 20:11     서울특별시 양천구 목2동 목동중앙북로101      우편번호없음       x좌표없음
4         2020.1.2 0:31        서울특별시 양천구 목3동 등촌로142      우편번호없음       x좌표없음
...                 ...                         ...         ...         ...
34192  2020.12.31 19:20        서울특별시 양천구 목1동목동동로210      우편번호없음       x좌표없음
34193  2020.12.31 19:48  서울특별시 양천구 신월동 신곡시장(백십자약국)       우편번호없음       x좌표없음
34194  2020.12.31 20:54         서울특별시 양천구 신정동 홍익병원       우편번호없음       x좌표없음
34195  2020.12.31 21:22         서울특별시 양천구 신정동 313-4  126.864035  37.5192387
34196  2020.12.31 23:12        서울특별시 양천구 신월3동187-11   126.82548  37.5308555

[34197 rows x 4 columns]

In [7]:
sub_df.drop(['Unnamed: 0'],axis=1, inplace=True)

In [8]:
sub_df

                 단속일시                      단속장소            X            Y
0       2020.1.2 7:41  서울특별시 양천구 신정동 신정기독교 백화점    126.852776  37.51993246
1       2020.1.2 9:53        서울특별시 양천구 목2동가나안교회  126.8705496  37.54011619
2      2020.1.2 10:06          서울특별시 양천구 신정동 KB       우편번호없음        x좌표없음
3      2020.1.2 10:07          서울특별시 양천구 신정동 한전       우편번호없음        x좌표없음
4      2020.1.2 10:29     서울특별시 양천구 신정동 오마당황소곱창  126.8541115  37.51913742
..                ...                       ...          ...          ...
328  2020.10.20 15:58        서울특별시 양천구 신정동 1279  126.8773599  37.52064992
329   2020.12.3 21:05      서울특별시 양천구 신월4동오목로172  126.8565845  37.52506978
330  2020.12.17 11:20    서울특별시 양천구 신월동 신서초등학교건너   126.862465  37.52037923
331  2020.12.18 16:10        서울특별시 양천구 신정동 송죽공원  126.8338823  37.53975559
332  2020.12.22 14:32       서울특별시 양천구 목7동목동동로67   126.862489  37.51583908

[333 rows x 4 columns]

In [9]:
for i in range(len(main_df)):
    for j in range(len(sub_df)):
        if main_df.단속장소[i] == sub_df.단속장소[j]:
            main_df.X[i] = sub_df.X[j]
            main_df.Y[i] = sub_df.Y[j]

In [10]:
for i in range(len(main_df)):
    if main_df.X[i] == '우편번호없음':
        main_df.drop(i,axis=0,inplace=True)

In [11]:
main_df.X.value_counts()

126.855695     2577
126.854849      749
126.834302      692
126.874868      447
126.8382576     414
               ...
126.8585908       1
126.8558727       1
126.8610755       1
126.886722        1
126.840653        1
Name: X, Length: 462, dtype: int64

main_df.to_csv('전처리끝_좌표계 및 단속장소.csv',encoding='cp949')

# 김용재 여기 까지 3/10 16시 15분 기준

In [12]:
main_df = main_df.reset_index()
main_df = main_df.drop('index', axis = 1)

In [13]:
for i in range(len(main_df)):
    if  main_df['단속장소'][i] == '서울특별시 양천구 신정동 통합관제센터':
        main_df['X'][i] = 126.84144036910035
        main_df['Y'][i] = 37.51147278889875

In [14]:
main_df.to_csv('단속장소_위경도_전처리완료.csv', encoding = 'cp949')

## 3/10 20:30 황규범 다른위치로 찍힌 위경도 변경

In [15]:
df = pd.read_csv('단속장소_시간대별분할추가.csv', encoding= 'cp949')

### 단속장소별 단속건수 추가

In [16]:
df = df.drop('Unnamed: 0', axis = 1)
df.head()

,단속일시,단속장소,X,Y,단속시간대,단속건수
0,2020.1.1 11:14,서울특별시 양천구 목동 901-3,126.872374,37.537457,10:00 ~ 11:59,48
1,2020.1.1 13:15,서울특별시 양천구 신월동 88-31,126.835014,37.537113,12:00 ~ 13:59,17
2,2020.1.1 15:07,서울특별시 양천구 신정동 212-1,126.866868,37.509881,14:00 ~ 15:59,117
3,2020.1.2 7:03,서울특별시 양천구 신정동 327-3,126.863208,37.513498,06:00 ~ 07:59,19
4,2020.1.2 7:09,서울특별시 양천구 신정7 목동파크자이아파트 정문,126.855695,37.515174,06:00 ~ 07:59,0

In [17]:
vc_df = df['단속장소'].value_counts()

In [18]:
df['단속장소'].value_counts().index[1]

'서울특별시 양천구 신정7 목동제일교회 '

In [19]:
df['단속장소'].value_counts()[1]

586

In [20]:
df['단속건수'] = 0

In [21]:
def set_how_much(df, df2):
    for i in range(len(df)):
        for j in range(len(df2)):
            if df['단속장소'][i].strip() == df2.index[j].strip():
                df['단속건수'][i] = df2[j]
    return df

In [22]:
set_how_much(df, vc_df)
df

C:\Users\bany9\AppData\Local\Temp/ipykernel_43412/1921944679.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['단속건수'][i] = df2[j]

,단속일시,단속장소,X,Y,단속시간대,단속건수
0,2020.1.1 11:14,서울특별시 양천구 목동 901-3,126.872374,37.537457,10:00 ~ 11:59,48
1,2020.1.1 13:15,서울특별시 양천구 신월동 88-31,126.835014,37.537113,12:00 ~ 13:59,17
2,2020.1.1 15:07,서울특별시 양천구 신정동 212-1,126.866868,37.509881,14:00 ~ 15:59,117
3,2020.1.2 7:03,서울특별시 양천구 신정동 327-3,126.863208,37.513498,06:00 ~ 07:59,19
4,2020.1.2 7:09,서울특별시 양천구 신정7 목동파크자이아파트 정문,126.855695,37.515174,06:00 ~ 07:59,556
...,...,...,...,...,...,...
24617,2020.12.31 18:20,서울특별시 양천구 신정동 1094,126.862468,37.522192,18:00 ~ 19:59,8
24618,2020.12.31 19:20,서울특별시 양천구 목1동목동동로210,126.864427,37.527366,18:00 ~ 19:59,33
24619,2020.12.31 20:54,서울특별시 양천구 신정동 홍익병원,126.863634,37.528603,20:00 ~ 21:59,123
24620,2020.12.31 21:22,서울특별시 양천구 신정동 313-4,126.864035,37.519239,20:00 ~ 21:59,45
24621,2020.12.31 23:12,서울특별시 양천구 신월3동187-11,126.825480,37.530856,22:00 ~ 23:59,15

In [23]:
df.to_csv('단속장소_단속시간대_단속건수추가.csv', encoding='cp949')

### 단속장소 화곡동 제거

In [24]:
df[df['단속장소'] == '서울특별시 양천구 신월동 강구PC']

,단속일시,단속장소,X,Y,단속시간대,단속건수
465,2020.1.8 16:17,서울특별시 양천구 신월동 강구PC,126.852259,37.553417,16:00 ~ 17:59,25
580,2020.1.9 16:04,서울특별시 양천구 신월동 강구PC,126.852259,37.553417,16:00 ~ 17:59,25
2750,2020.2.5 16:48,서울특별시 양천구 신월동 강구PC,126.852259,37.553417,16:00 ~ 17:59,25
3434,2020.2.13 16:05,서울특별시 양천구 신월동 강구PC,126.852259,37.553417,16:00 ~ 17:59,25
5044,2020.3.5 16:27,서울특별시 양천구 신월동 강구PC,126.852259,37.553417,16:00 ~ 17:59,25
5167,2020.3.6 16:29,서울특별시 양천구 신월동 강구PC,126.852259,37.553417,16:00 ~ 17:59,25
6865,2020.3.31 16:12,서울특별시 양천구 신월동 강구PC,126.852259,37.553417,16:00 ~ 17:59,25
9710,2020.5.13 15:44,서울특별시 양천구 신월동 강구PC,126.852259,37.553417,14:00 ~ 15:59,25
11783,2020.6.8 15:35,서울특별시 양천구 신월동 강구PC,126.852259,37.553417,14:00 ~ 15:59,25
12132,2020.6.12 15:23,서울특별시 양천구 신월동 강구PC,126.852259,37.553417,14:00 ~ 15:59,25
12485,2020.6.17 15:31,서울특별시 양천구 신월동 강구PC,126.852259,37.553417,14:00 ~ 15:59,25
13480,2020.7.1 15:43,서울특별시 양천구 신월동 강구PC,126.852259,37.553417,14:00 ~ 15:59,25
14072,2020.7.9 15:43,서울특별시 양천구 신월동 강구PC,126.852259,37.553417,14:00 ~ 15:59,25
15723,2020.8.4 15:23,서울특별시 양천구 신월동 강구PC,126.852259,37.553417,14:00 ~ 15:59,25
16619,2020.8.19 15:30,서울특별시 양천구 신월동 강구PC,126.852259,37.553417,14:00 ~ 15:59,25
17085,2020.8.25 15:27,서울특별시 양천구 신월동 강구PC,126.852259,37.553417,14:00 ~ 15:59,25
17574,2020.9.1 16:40,서울특별시 양천구 신월동 강구PC,126.852259,37.553417,16:00 ~ 17:59,25
19221,2020.9.23 16:36,서울특별시 양천구 신월동 강구PC,126.852259,37.553417,16:00 ~ 17:59,25
19222,2020.9.23 16:36,서울특별시 양천구 신월동 강구PC,126.852259,37.553417,16:00 ~ 17:59,25
19223,2020.9.23 16:36,서울특별시 양천구 신월동 강구PC,126.852259,37.553417,16:00 ~ 17:59,25
21756,2020.11.2 16:24,서울특별시 양천구 신월동 강구PC,126.852259,37.553417,16:00 ~ 17:59,25
23283,2020.11.27 15:56,서울특별시 양천구 신월동 강구PC,126.852259,37.553417,14:00 ~ 15:59,25
23508,2020.12.2 16:39,서울특별시 양천구 신월동 강구PC,126.852259,37.553417,16:00 ~ 17:59,25
24114,2020.12.14 17:02,서울특별시 양천구 신월동 강구PC,126.852259,37.553417,16:00 ~ 17:59,25
24331,2020.12.21 15:30,서울특별시 양천구 신월동 강구PC,126.852259,37.553417,14:00 ~ 15:59,25

In [25]:
df.drop(130, axis = 0, inplace = True)

In [26]:
df.reset_index(inplace = True)
df.drop('index', axis = 1, inplace = True)

### 단속장소 중복제거

In [27]:
df = df.drop_duplicates('단속장소', keep = 'first')
df = df[['단속장소', 'X', 'Y', '단속건수']]

In [28]:
df = df.reset_index()
df = df.drop('index', axis = 1)

In [29]:
df.to_csv('단속장소_단속시간대_단속건수_중복제거.csv', encoding = 'cp949')

### '단속건수' 20 이하 제거

In [30]:
df_2 = df[df['단속건수'] > 20]

In [31]:
df_2.reset_index(inplace = True)

In [32]:
df_2.drop('index', axis =1, inplace = True)

D:\Anaconda3\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [33]:
df_2

                            단속장소           X          Y  단속건수
0             서울특별시 양천구 목동 901-3  126.872374  37.537457    48
1            서울특별시 양천구 신정동 212-1  126.866868  37.509881   117
2    서울특별시 양천구 신정7 목동파크자이아파트 정문   126.855695  37.515174   556
3       서울특별시 양천구 신정동 신정기독교 백화점   126.852776  37.519932   261
4              서울특별시 양천구 신정동 311  126.857833  37.514988   131
..                           ...         ...        ...   ...
293    서울특별시 양천구 목동 목1동 서가앤쿡 목동점  126.869250  37.525320   237
294       서울특별시 양천구 목동 보미진온누리약국   126.864081  37.549686   103
295           서울특별시 양천구 목5동목동5단지  126.880442  37.534409    25
296       서울특별시 양천구 목5동목동서로133-4  126.876051  37.531956    21
297   서울특별시 양천구 신정동 GS더프레시 양천신은점  126.833006  37.512891    21

[298 rows x 4 columns]

In [34]:
df_2.to_csv('단속건수20이하.csv', encoding= 'cp949')

### '단속건수' 36 이하 제거

In [35]:
df_3 = df[df['단속건수'] > 36]

In [36]:
df_3.reset_index(inplace = True)
df_3.drop('index', axis = 1, inplace = True)

D:\Anaconda3\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [37]:
df_3

                            단속장소           X          Y  단속건수
0             서울특별시 양천구 목동 901-3  126.872374  37.537457    48
1            서울특별시 양천구 신정동 212-1  126.866868  37.509881   117
2    서울특별시 양천구 신정7 목동파크자이아파트 정문   126.855695  37.515174   556
3       서울특별시 양천구 신정동 신정기독교 백화점   126.852776  37.519932   261
4              서울특별시 양천구 신정동 311  126.857833  37.514988   131
..                           ...         ...        ...   ...
151          서울특별시 양천구 목동 현대파크빌   126.867165  37.542323   143
152      서울특별시 양천구 신월동 신월3동 우체국   126.828695  37.534653    48
153     서울특별시 양천구 신월1동곰달래로11길 56  126.834302  37.526589    57
154    서울특별시 양천구 목동 목1동 서가앤쿡 목동점  126.869250  37.525320   237
155       서울특별시 양천구 목동 보미진온누리약국   126.864081  37.549686   103

[156 rows x 4 columns]

In [38]:
df_3.to_csv('단속건수36이하.csv', encoding= 'cp949')

### x, y 값이 모두같은 단속장소 제거

단속장소 명이 다르게 기입되어 있지만 X, Y 좌표 모두 동일한 행들의
단속장소를 합한 후 중복 제거

In [39]:
df_3['xy'] = 0

C:\Users\bany9\AppData\Local\Temp/ipykernel_43412/4149871399.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_3['xy'] = 0

In [41]:
for i in range(len(df_3)):
    df_3['xy'][i] = df_3['X'][i],',',df_3['Y'][i]
    df_3['xy'][i] = df_3['X'][i],df_3['Y'][i]

C:\Users\bany9\AppData\Local\Temp/ipykernel_43412/1537673801.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_3['xy'][i] = df_3['X'][i],',',df_3['Y'][i]
D:\Anaconda3\lib\site-packages\pandas\core\indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
D:\Anaconda3\lib\site-packages\pandas\core\series.py:1056: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cacher_needs_updating = self._check_is_chained_assignment_possible()

In [43]:
for i in range(len(df_3) -1):
    if df_3['xy'][i] == df_3['xy'][i+1]:
        df_3['단속건수'][i] += df_3['단속건수'][i+1]

df_3.drop_duplicates('xy', keep = 'first', inplace = True)

C:\Users\bany9\AppData\Local\Temp/ipykernel_43412/3336254988.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_3['단속건수'][i] += df_3['단속건수'][i+1]
D:\Anaconda3\lib\site-packages\pandas\util\_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

In [46]:
df_3.reset_index(inplace = True)
df_3.drop('index', axis = 1, inplace = True)

D:\Anaconda3\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [48]:
df_3.drop('xy', axis = 1, inplace = True)

D:\Anaconda3\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [50]:
df_3.to_csv('단속장소_최종중복제거.csv', encoding = 'cp949')