In [53]:
import pandas as pd
from haversine import haversine

In [54]:
def set_dis_from_first(df, point):
    for i in range(len(df)):
        df['dis_from_first'][i] = haversine((point['X'], point['Y']), (df['X'][i], df['Y'][i])) * 1000

In [55]:
def hav_dis(df, a, b):
    h = (df['X'][a], df['Y'][a])
    j = (df['X'][b], df['Y'][b])
    dis = haversine(h,j) * 1000
    return dis

In [56]:
def set_dis_to_next_num(df):
    for i in range(len(df)-1):
        d = hav_dis(df, i, i+1)
        df['dis'][i] = d
    return df

In [57]:
df_8 = pd.read_csv('8.csv', encoding = 'cp949')
df_10 = pd.read_csv('10.csv', encoding = 'cp949')
df_12 = pd.read_csv('12.csv', encoding = 'cp949')
df_14 = pd.read_csv('14.csv', encoding = 'cp949')
df_16 = pd.read_csv('16.csv', encoding = 'cp949')
df_18 = pd.read_csv('18.csv', encoding = 'cp949')

In [58]:
def sep_and_num(df):
    x_cen = (df['X'].min() + df['X'].max())/2
    y_cen = (df['Y'].min() + df['Y'].max())/2
    df1 = df[(df['X'] <= x_cen) & (df['Y'] >= y_cen) ] # 좌측 상단
    df2 = df[(df['X'] <= x_cen) & (df['Y'] < y_cen) ] # 죄측 하단
    df3 = df[(df['X'] > x_cen) & (df['Y'] < y_cen) ] # 우측 하단
    df4 = df[(df['X'] > x_cen) & (df['Y'] >= y_cen)] # 우측 상단
    for i in range(1,5):
        locals()[f'df{i}'].reset_index(inplace = True, drop = True)
    p1 = df1[df1['Y'] == df1['Y'].max()]
    p2 = df2[df2['X'] == df2['X'].min()]
    p3 = df3[df3['X'] == df3['X'].min()]
    p4 = df4[df4['Y'] == df4['Y'].min()]
    for i in range(1,5):
        locals()[f'df{i}']['dis_from_first'] = 0
    
    set_dis_from_first(df1, p1)
    set_dis_from_first(df2, p2)
    set_dis_from_first(df3, p3)
    set_dis_from_first(df4, p4)
    for i in range(1,5):
        locals()[f'df{i}']['label'] = i
    for i in range(1,5):
        locals()[f'df{i}'] = locals()[f'df{i}'].sort_values('dis_from_first')
    for i in range(1,5):
        locals()[f'df{i}'].reset_index(inplace = True, drop = True)
    
    df_final = df1.append(df2)
    df_final = df_final.append(df3)
    df_final = df_final.append(df4)
    df_final.reset_index(inplace = True, drop= True)
    df_final['number'] = 0
    for i in range(len(df_final)):
        df_final['number'][i] = df_final.index[i]
        
    df_final['dis'] = 0
    set_dis_to_next_num(df_final)
    len_div_by_3 = df_final['number'].max() // 3
    df_final['label_by_3'] = 0
    df_final.loc[ :len_div_by_3]['label_by_3'] = 1
    df_final.loc[len_div_by_3 + 1 : len_div_by_3 * 2]['label_by_3'] = 2
    df_final.loc[len_div_by_3*2 + 1 : ]['label_by_3'] = 3
    
    return df_final

In [59]:
for i in range(8, 19, 2):
    globals()[f'df_{i}_1'] = sep_and_num(globals()[f'df_{i}'])

C:\Users\bany9\AppData\Local\Temp/ipykernel_31548/494353268.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  locals()[f'df{i}']['dis_from_first'] = 0
C:\Users\bany9\AppData\Local\Temp/ipykernel_31548/98491907.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['dis_from_first'][i] = haversine((point['X'], point['Y']), (df['X'][i], df['Y'][i])) * 1000
C:\Users\bany9\AppData\Local\Temp/ipykernel_31548/494353268.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  locals()[f'df{i}']['label'] = i
C:\Users\bany9\AppData\Local\Temp/ipykernel_31548/494353268.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final['number'][i] = df_final.index[i]
C:\Users\bany9\AppData\Local\Temp/ipykernel_31548/3761305484.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['dis'][i] = d
C:\Users\bany9\AppData\Local\Temp/ipykernel_31548/494353268.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final.loc[ :len_div_by_3]['label_by_3'] = 1
C:\Users\bany9\AppData\Local\Temp/ipykernel_31548/494353268.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final.loc[len_div_by_3 + 1 : len_div_by_3 * 2]['label_by_3'] = 2
C:\Users\bany9\AppData\Local\Temp/ipykernel_31548/494353268.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final.loc[len_div_by_3*2 + 1 : ]['label_by_3'] = 3

In [60]:
df_10_1

,Unnamed: 0,단속장소,X,Y,단속시간대,단속건수,dis_from_k,num,dis,dis_from_first,label,number,label_by_3
0,0,서울특별시 양천구 신월3동신원초교,126.829355,37.545372,10:00 ~ 11:59,4,0,0,132,0,1,0,1
1,1,서울특별시 양천구 신월동 수명산롯데캐슬아파트,126.828413,37.544168,10:00 ~ 11:59,13,132,1,218,132,1,1,1
2,2,서울특별시 양천구 신월동 신월중학교,126.828963,37.541024,10:00 ~ 11:59,13,293,2,163,293,1,2,1
3,3,서울특별시 양천구 신월동 강서경찰서,126.830222,37.539764,10:00 ~ 11:59,8,386,3,277,386,1,3,1
4,4,서울특별시 양천구 신월동 273,126.828015,37.537837,10:00 ~ 11:59,3,523,4,74,523,1,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,120,서울특별시 양천구 목목동2차성원아파트,126.864154,37.542289,10:00 ~ 11:59,2,0,120,115,1038,4,120,3
121,121,서울특별시 양천구 목동 성원아파트,126.863172,37.542853,10:00 ~ 11:59,42,115,121,611,1117,4,121,3
122,122,서울특별시 양천구 목목동대우마이빌,126.866933,37.549534,10:00 ~ 11:59,20,573,122,830,1450,4,122,3
123,123,서울특별시 양천구 신정3 목동메디컬복합센터,126.873726,37.544353,10:00 ~ 11:59,8,1073,123,200,1297,4,123,3
124,124,서울특별시 양천구 목2동어바니엘,126.874772,37.546796,10:00 ~ 11:59,6,1218,124,0,1497,4,124,3

In [52]:
df_8_1.to_csv('8_final.csv', encoding = 'cp949')
df_10_1.to_csv('10_final.csv', encoding = 'cp949')
df_12_1.to_csv('12_final.csv', encoding = 'cp949')
df_14_1.to_csv('14_final.csv', encoding = 'cp949')
df_16_1.to_csv('16_final.csv', encoding = 'cp949')
df_18_1.to_csv('18_final.csv', encoding = 'cp949')